name: test

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*' # Don't run these tests twice when cutting a new version.

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
        os:
          - "ubuntu-20.04"
          - "macos-10.15"
          - "windows-2019"

    services:
      postgres:
        image: postgres:9.5.25-alpine
        env:
          POSTGRES_USER: scalarstop
          POSTGRES_PASSWORD: changeme
          POSTGRES_DB: train_store
        ports:
          - "5432:5432"

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip and poetry
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install poetry
        poetry config virtualenvs.in-project true
  
    - name: Install the package
      run: make install

    - name: Check formatting
      if: startsWith(matrix.os,'ubuntu')
      run: make fmt-check

    - name: Run lint
      if: startsWith(matrix.os,'ubuntu')
      run: make lint
  
    - name: Run tests
      run: make test
      env:
        TRAIN_STORE_CONNECTION_STRING: "postgresql://scalarstop:changeme@localhost:5432/train_store"
