name: test-windows

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*' # Don't run these tests twice when cutting a new version.

jobs:
  test-windows:
    runs-on: "windows-2019"
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
    - name: Check out ScalarStop code from GitHub
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Pip and Poetry
      run: |
        python3 -m pip install --upgrade pip wheel poetry
        poetry config virtualenvs.in-project true
  
    - name: Cache the Poetry virtualenv
      uses: actions/cache@v2
      with:
        path: .venv
        key: windows-2019-python-${{ steps.setup-python.outputs.python-version }}-pyproject-${{ hashFiles('**/pyproject.toml') }}

    - name: Install ScalarStop and its Python dependencies
      run: make install

    - name: Run ScalarStop unit tests
      run: make test
