name: test-mac

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*' # Don't run these tests twice when cutting a new version.

jobs:
  test-mac:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache the Poetry virtualenv
      uses: actions/cache@v2
      with:
        path: .venv
        key: ${{ runner.os }}-python-${{ matrix.python-version }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-python-${{ matrix.python-version }}-poetry-

    - name: Install pip and poetry
      run: |
        python3 -m pip install --upgrade pip wheel poetry
        poetry config virtualenvs.in-project true
  
    - name: Install the package
      run: make install

    - name: Run tests
      run: make test
